name: Rust CI

on:
  push:
    branches:
      - '*test*'
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libx11-dev

      - name: Run tests
        run: |
          cargo build --verbose
          cargo test --verbose

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build the release binary
        run: |
          cargo build --release

      - name: Create GitHub Release and Upload Binary
        run: |
          VERSION=${GITHUB_REF##*/}
          mv target/release/birdfetch target/release/birdfetch-${VERSION}
          echo "Binary name: birdfetch-${VERSION}"
          gh release create "v${VERSION}" target/release/birdfetch-${VERSION} --title "Release v${VERSION}" --notes "Release notes for v${VERSION}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
